#SQL DA TABELA IMOVEIS
SQL_CRIA_IMOVEL = '''
                INSERT INTO IMOVEIS (ID_CORR, ID_PROP, ID_CIDADE,ID_BAIRRO,CATEGORIA,FORMA,LADO_ESQ,LADO_DIR,LADO_FRE,
                                    LADO_FUN,TOTAL,TOPOGRAFIA,AREA_UTIL,CONSTRUIDA,EDICULA,AREA_INFO,TIPO,SUBTIPO,ENDERECO_IMOVEL,
                                    NUMERO,CEP,END_INFO,PLACA,DATA_PLACA,DATA_VISITA,DATA_ULTIMA_VIS,URL,COD_ANUNCIO,ANUNCIO_INFO,
                                    VALOR_IMOVEL,VALOR_VENDA,CORRETAGEM,REPASSE_IMOB)
                VALUES (%S, %S, %S, %S, %S, %S ,%S, %S, %S ,%S, %S, %S, %S, %S, %S,
                         %S, %S, %S, %S ,%S, %S, %S, %S, %S, %S, %S, %S,%S,%S,%S,%S,%S,%S);
'''

SQL_CRIA_IMOVEL_DESC = '''
                    INSERT INTO IMOVEL_DESC (ID_IMOB,VAGAS,BANHEIRO,SUITE,DORMITORIOS,AREA_SERVICO,COPA,
                    EDICULA ,LAREIRA ,PORTAO_ELEC ,HIDROMSG ,PISO ,SACADA ,SALA_VIST ,SALA_ESTAR ,SOTAO ,AMARINHO ,
                    COZINHA ,ESCRITORIO ,LAVABO ,SALA_JANTAR ,VARANDA ,CLARABOIA ,DEP_EMPREGADA ,GARAGE ,LIVING_ROOM ,
                    QUINTAL ,SALA_TV ,W_C_EMPREGADA ,CLOSET ,DESPENSA ,CHURRASQUEIRA ,PORTARIA_24H ,SALAO_FESTA ,
                    JD_INVERNO ,QUADRA ,SAUNA ,PISCINA ,ENTRADA_INDEP ,QUADRA_TENIS ,PLAYGROUND ,SALA_GINASTICA)
                    VALUES (%S, %S, %S, %S, %S, %S ,%S, %S, %S ,%S, %S, %S, %S, %S, %S,%S, %S, %S, %S ,%S, %S, 
                            %S, %S, %S, %S, %S, %S,%S,%S,%S,%S,%S,%S, %S,%S,%S,%S,%S,%S,%S,%S,%S);
'''

SQL_ATUALIZA_DESC = '''UPDATE IMOVEL_DESC SET VAGAS =%S,BANHEIRO =%S,SUITE =%S, DORMITORIOS =%S,AREA_SERVICO =%S,COPA =%S,EDICULA =%S,
                        LAREIRA =%S,PORTAO_ELEC =%S,HIDROMSG =%S,PISO =%S,SACADA =%S,SALA_VIST =%S,SALA_ESTAR =%S,SOTAO =%S,AMARINHO =%S,
                        COZINHA =%S,ESCRITORIO =%S,LAVABO =%S,SALA_JANTAR =%S,VARANDA =%S,CLARABOIA =%S,DEP_EMPREGADA =%S,GARAGE =%S,
                        LIVING_ROOM =%S,QUINTAL =%S,SALA_TV =%S,W_C_EMPREGADA =%S,CLOSET =%S,DESPENSA =%S,CHURRASQUEIRA =%S,PORTARIA_24H =%S,SALAO_FESTA =%S,
                        JD_INVERNO =%S,QUADRA =%S,SAUNA =%S,PISCINA =%S,ENTRADA_INDEP =%S,QUADRA_TENIS =%S,PLAYGROUND =%S,SALA_GINASTICA =%S WHERE ID_DESC = %S
'''

SQL_DELETA_IMOVEL = 'DELETE FROM IMOVEIS WHERE ID_IMOB = %S'

SQL_ATUALIZA_IMOVEIS = ''' UPDATE IMOVEIS SET  ID_CORR=%S, ID_PROP=%S, ID_CIDADE=%S,ID_BAIRRO=%S,
                                    CATEGORIA=%S,FORMA=%S,LADO_ESQ=%S,LADO_DIR=%S,LADO_FRE=%S,
                                    LADO_FUN=%S,TOTAL=%S,TOPOGRAFIA=%S,AREA_UTIL=%S,CONSTRUIDA=%S,EDICULA=%S,
                                    AREA_INFO=%S,TIPO=%S,SUBTIPO=%S,ENDERECO_IMOVEL=%S,
                                    NUMERO=%S,CEP=%S,END_INFO=%S,PLACA=%S,DATA_PLACA=%S,DATA_VISITA=%S,DATA_ULTIMA_VIS=%S,
                                    URL=%S,COD_ANUNCIO=%S,ANUNCIO_INFO=%S,
                                     VALOR_IMOVEL=%S,VALOR_VENDA=%S,CORRETAGEM=%S,REPASSE_IMOB=%S WHERE ID_IMOB=%S;
    '''

SQL_BUSCA_LISTA_IMOB = 'SELECT ID_IMOB,CATEGORIA,CIDADE,BAIRRO,ENDERECO_IMOVEL,NOME,CELULAR FROM IMOVEIS LEFT JOIN PROPRIETARIOS ON IMOVEIS.ID_PROP = PROPRIETARIOS.ID_PROP' \
                       ' JOIN CIDADE ON CIDADE.ID_CID = IMOVEIS.ID_CIDADE JOIN BAIRRO ON BAIRRO.ID_BAIRRO = IMOVEIS.ID_BAIRRO'


SQL_BUSCA_IMOB_ID ='''SELECT * FROM IMOVEIS LEFT JOIN PROPRIETARIOS ON IMOVEIS.ID_PROP = PROPRIETARIOS.ID_PROP 
                    JOIN CIDADE ON CIDADE.ID_CID = IMOVEIS.ID_CIDADE 
                    JOIN BAIRRO ON BAIRRO.ID_BAIRRO = IMOVEIS.ID_BAIRRO 
                    LEFT JOIN CORRETORES ON IMOVEIS.ID_CORR = CORRETORES.ID_CORR 
                    LEFT JOIN IMOVEL_DESC ON IMOVEIS.ID_IMOB = IMOVEL_DESC.ID_IMOB
                    WHERE IMOVEIS.ID_IMOB = %S
'''
 
#SQL DA TABELA PROPEITARIOS

SQL_DELETA_PROPRIETARIO = 'DELETE FROM PROPRIETARIOS WHERE ID_PROP = %S'


SQL_CRIA_PROPRIETARIO = 'INSERT INTO PROPRIETARIOS (NOME, CPF_CNPJ, RG_INSC_ETAD, SEXO, ENDERECO, CEP , NUMERO, PESSOA, RAZAO ,' \
                        'TELEFONE, CELULAR, WHATAPPS, EMAIL,CAPITAL, PATRIMONIO, ATIVIDADE, ID_CIDADE, ID_BAIRRO) VALUES (%S,%S,%S,%S,%S,%S,%S,%S,%S,%S,%S,%S,%S,%S,%S,%S,%S,%S)'

SQL_ATUALIZA_PROPRIETARIO = 'UPDATE PROPRIETARIOS SET NOME=%S, CPF_CNPJ=%S, RG_INSC_ETAD=%S, SEXO=%S, ENDERECO=%S, CEP=%S , NUMERO=%S, PESSOA=%S, RAZAO=%S ,' \
                        'TELEFONE=%S, CELULAR=%S, WHATAPPS=%S, EMAIL=%S,CAPITAL=%S, PATRIMONIO=%S, ATIVIDADE=%S, ID_CIDADE=%S, ID_BAIRRO=%S WHERE ID_PROP=%S'

SQL_BUSCAR_LISTA_PROP = 'SELECT ID_PROP, NOME, CPF_CNPJ, RG_INSC_ETAD, ENDERECO, TELEFONE, EMAIL, ID_CIDADE, ID_BAIRRO FROM PROPRIETARIOS'

SQL_FIND_PROP_BY_NAME = 'SELECT ID_PROP, NOME, CPF_CNPJ, RG_INSC_ETAD, ENDERECO, TELEFONE, EMAIL, ID_CIDADE, ID_BAIRRO FROM PROPRIETARIOS WHERE NOME LIKE %S'

SQL_PROP_POR_ID = 'SELECT * FROM PROPRIETARIOS ' \
                  'LEFT JOIN CIDADE ON PROPRIETARIOS.ID_CIDADE = CIDADE.ID_CID ' \
                  'LEFT JOIN BAIRRO ON PROPRIETARIOS.ID_BAIRRO = BAIRRO.ID_BAIRRO WHERE ID_PROP=%S'


#SQL DA TABELA CORRETORES
SQL_DELETA_CORRETOR = 'DELETE FROM CORRETORES WHERE ID_CORR = %S'

SQL_CRIA_CORRETORES = 'INSERT INTO CORRETORES (USUARIO,EMAIL,NOME,CRECI,CELULAR,CPF,ENDERECO,SENHA,ID_CIDADE, ID_BAIRRO) VALUES (%S,%S,%S,%S,%S,%S,%S,%S,%S,%S)'

SQL_ATUALIZA_CORRETORES = 'UPDATE CORRETORES SET USUARIO=%S,EMAIL=%S,NOME=%S,CRECI=%S,CELULAR=%S,CPF=%S,ENDERECO=%S,SENHA=%S,ID_CIDADE=%S,ID_BAIRRO=%S  WHERE ID_CORR=%S'

SQL_BUSCA_LISTA_CORRETORES = "SELECT ID_CORR, USUARIO, EMAIL,NOME,CRECI,CELULAR,CPF,ENDERECO,SENHA,ID_CIDADE, ID_BAIRRO FROM CORRETORES WHERE USUARIO!='ADMIN'"

SQL_BUSCA_CORR_ID = 'SELECT ID_CORR, USUARIO, EMAIL,NOME,CRECI,CELULAR,CPF,ENDERECO,SENHA,ID_CIDADE, ID_BAIRRO FROM CORRETORES WHERE USUARIO=%S OR EMAIL=%S'

SQL_FIND_CORR_BY_NAME = "SELECT ID_CORR, USUARIO, EMAIL,NOME,CRECI,CELULAR,CPF,ENDERECO,SENHA,ID_CIDADE, ID_BAIRRO FROM CORRETORES WHERE NOME LIKE %S AND USUARIO!='ADMIN'"

SQL_BUSCA_CORR_POR_ID = 'SELECT * FROM CORRETORES ' \
                        'LEFT JOIN CIDADE ON CORRETORES.ID_CIDADE = CIDADE.ID_CID ' \
                        'LEFT JOIN BAIRRO ON CORRETORES.ID_BAIRRO = BAIRRO.ID_BAIRRO WHERE ID_CORR=%S'


#SQL DA TABELA FINANCEIRO
SQL_BUSCA_FIN_ID = 'SELECT * FROM FINANCEIRO WHERE ID_IMOB_FIN = %S'

SQL_DELETA_FIN = 'DELETE FROM FINANCEIRO WHERE ID_IMOB_FIN = %S'

SQL_CRIA_FIN = 'INSERT INTO FINANCEIRO (HONORARIOS_CORR,PORCENTAGEM_CORR, HONORARIOS_IMOB, PORCENTAGEM_IMOB ,ID_CORR_FIN, ID_IMOB_FIN) VALUES(%S,%S,%S,%S,%S,%S)'

SQL_ATUALIZA_FIN = 'UPDATE FINANCEIRO SET HONORARIOS_CORR=%S,PORCENTAGEM_CORR=%S, HONORARIOS_IMOB=%S, PORCENTAGEM_IMOB=%S, ID_CORR_FIN=%S WHERE ID_FIN=%S'

SQL_LISTA_FIN = 'SELECT FINANCEIRO.ID_FIN, FINANCEIRO.HONORARIOS_CORR, FINANCEIRO.PORCENTAGEM_CORR,FINANCEIRO.HONORARIOS_IMOB, FINANCEIRO.PORCENTAGEM_IMOB, ' \
                'CORRETORES.NOME, IMOVEIS.ENDERECO_IMOVEL , IMOVEIS.VALOR_VENDA, IMOVEIS.HONORARIOS,FINANCEIRO.ID_CORR_FIN FROM FINANCEIRO ' \
                'INNER JOIN CORRETORES ON FINANCEIRO.ID_CORR_FIN = ID_CORR ' \
                'INNER JOIN IMOVEIS ON FINANCEIRO.ID_IMOB_FIN = IMOVEIS.ID_IMOB'

SQL_LISTA_FIN_CORR = 'SELECT FINANCEIRO.ID_FIN, FINANCEIRO.HONORARIOS_CORR, FINANCEIRO.PORCENTAGEM_CORR,FINANCEIRO.HONORARIOS_IMOB, FINANCEIRO.PORCENTAGEM_IMOB, ' \
                'CORRETORES.NOME, IMOVEIS.ENDERECO_IMOVEL , IMOVEIS.VALOR_VENDA, IMOVEIS.HONORARIOS,FINANCEIRO.ID_CORR_FIN FROM FINANCEIRO ' \
                'INNER JOIN CORRETORES ON FINANCEIRO.ID_CORR_FIN = ID_CORR ' \
                'INNER JOIN IMOVEIS ON FINANCEIRO.ID_IMOB_FIN = IMOVEIS.ID_IMOB WHERE FINANCEIRO.ID_CORR_FIN = %S'

#TIPOS
SQL_CRIA_TIPOS = 'INSERT INTO TIPOS (ID_TIPO,TIPO) VALUES(%S,%S)'
SQL_LISTA_TIPOS = 'SELECT * FROM TIPOS'


#CIDADE E BAIRRO
SQL_CRIA_CIDADE = 'INSERT INTO CIDADE (ID_CID,CIDADE) VALUES(%S,%S)'
SQL_LISTA_CIDADE = 'SELECT * FROM CIDADE'
SQL_CRIA_BAIRRO = 'INSERT INTO BAIRRO (ID_BAIRRO,BAIRRO,CIDADE_ID_CID) VALUES(%S,%S, %S)'
SQL_LISTA_BAIRRO = 'SELECT * FROM BAIRRO INNER JOIN CIDADE ON BAIRRO.CIDADE_ID_CID = CIDADE.ID_CID'


#FILTROS
SQL_FILTRA_CIDADE = 'SELECT ID_IMOB,CATEGORIA,CIDADE,BAIRRO,ENDERECO_IMOVEL,NOME,CELULAR FROM IMOVEIS LEFT JOIN PROPRIETARIOS ON IMOVEIS.ID_PROP = PROPRIETARIOS.ID_PROP' \
                       ' JOIN CIDADE ON CIDADE.ID_CID = IMOVEIS.ID_CIDADE JOIN BAIRRO ON BAIRRO.ID_BAIRRO = IMOVEIS.ID_BAIRRO WHERE IMOVEIS.ID_BAIRRO WHERE IMOVEIS.ID_CIDADE= %S'

SQL_FILTRA_PROP = 'SELECT ID_IMOB,CATEGORIA,CIDADE,BAIRRO,ENDERECO_IMOVEL,NOME,CELULAR FROM IMOVEIS LEFT JOIN PROPRIETARIOS ON IMOVEIS.ID_PROP = PROPRIETARIOS.ID_PROP' \
                       ' JOIN CIDADE ON CIDADE.ID_CID = IMOVEIS.ID_CIDADE JOIN BAIRRO ON BAIRRO.ID_BAIRRO = IMOVEIS.ID_BAIRRO WHERE IMOVEIS.ID_PROP = %S'

SQL_FILTRO_BAIRRO = 'SELECT ID_IMOB,CATEGORIA,CIDADE,BAIRRO,ENDERECO_IMOVEL,NOME,CELULAR FROM IMOVEIS LEFT JOIN PROPRIETARIOS ON IMOVEIS.ID_PROP = PROPRIETARIOS.ID_PROP' \
                       ' JOIN CIDADE ON CIDADE.ID_CID = IMOVEIS.ID_CIDADE JOIN BAIRRO ON BAIRRO.ID_BAIRRO = IMOVEIS.ID_BAIRRO WHERE WHERE IMOVEIS.ID_BAIRRO = %S'